export type AppErrorCode =
  | 'VALIDATION_FAILED'
  | 'INVALID_PLAN_INPUT'
  | 'INVALID_NDJSON'
  | 'SCHEMA_VERSION_UNSUPPORTED'
  | 'SIMULATION_ERROR'
  | 'NEGATIVE_BALANCE'
  | 'WITHDRAWAL_CONVERGENCE'
  | 'CLAUDE_API_KEY_MISSING'
  | 'CLAUDE_API_KEY_INVALID'
  | 'CLAUDE_API_RATE_LIMITED'
  | 'CLAUDE_API_NETWORK_ERROR'
  | 'CLAUDE_API_TIMEOUT'
  | 'CLAUDE_RESPONSE_INVALID'
  | 'CLAUDE_FALLBACK_USED'
  | 'ONEDRIVE_AUTH_FAILED'
  | 'ONEDRIVE_PERMISSION_DENIED'
  | 'ONEDRIVE_NETWORK_ERROR'
  | 'ONEDRIVE_SYNC_CONFLICT'
  | 'ONEDRIVE_QUOTA_EXCEEDED'
  | 'PDF_PARSE_FAILED'
  | 'PDF_FORM_UNRECOGNIZED'
  | 'PDF_EXTRACTION_LOW_CONFIDENCE';

export interface AppError {
  code: AppErrorCode;
  message: string;
  details?: Record<string, string | number | boolean | null>;
  retryable: boolean;
  timestamp: string;
}
